### ISSUE TITLE
Set a hackathon theme

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Hackathon#2]
I think hackathons are great when they are themed! Since we have a nice mix of Programming/Design/Creative/Hardware/etc. I think it would be fantastic to have a "theme" for as many of these categories as possible.

**Comment by adilanchian** [comment]
Going to start this convo.

I think the thing we need to have is some broad-ish theme to help people come up with project ideas. I was thinking we can base the hackathon around making a tool that can help someone begin their dev journey. 

Another idea, maybe projects around ways to promote your projects such as auto resume builders or some sort of tool to constantly keep your portfolio site up to date? Thoughts?

**Comment by eddiejaoude** [comment]
I like the idea of resume builder! I think its always been an issue. There was the "OpenSource Report Card" which is now offline http://osrc.dfm.io, but something like that was awesome! 🤓

**Comment by eddiejaoude** [comment]
Lets do that, I have already thought of my idea!! 😎 😜

**Comment by DevBowser** [comment]
I really like the idea of a resume builder. If someone can 'hack' together a website that generates your resume based off github projects with URLs linking to your actual profile, I think this would benefit junior developers majorly.

**Comment by adilanchian** [comment]
Okay awesome!

So one theme we can add to a vote could be something along the lines of personal growth:
`Make a tool that can help you show off your work to others`
This can keep the scope broad so people can really use their creativity.

Another theme idea I had was to build a tool that can help bring a community closer together. Finally, the last one could be a free for all - "Make anything!"

**Comment by adilanchian** [comment]
We have decided to take this offline for some sensitive information regarding prizes. We will be continuing this on Discord.

**Comment by adilanchian** [comment]
Our themes have been decided and I have them written down locally. Will release these when the hackathon begins!
