### ISSUE TITLE
Finalize judging system

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Hackathon#3]
To declare final winners we need to figure out a way to get make it a fair judging. My thought was to get the viewers to vote on the final projects. If the there ends up being a tie, we can then put in our final votes. Open do discussion!

**Comment by stmoerman** [comment]
Definitely, think it's a good idea to give viewers the final votes - we can always give our personal votes afterward to give all contesters feedback if that's welcomed. By giving viewers the vote we keep it fair, I don't want anyone to come across as being biased if they potentially vote on one of their loyal viewers, right.

**Comment by adilanchian** [comment]
Sweet I 100% agree. Devpost gives us the option to have viewers add their own votes on projects which is perfect for this scenario.

We can then pick best project from each category :)

**Comment by swiftysix** [comment]
I have used http://www.streampoll.tv/index.php in the past and I find it really easy to setup and also pretty cool because it comes with a pie chart. But, it does not protect against bots...

I think letting the viewers vote is a really good idea. Just keep in mind that not everybody will have the same number of viewers. The streamers with lower viewer counts will most likely have a lower chance of winning. -> Probably important for everybody to focus on fun and not winning the price

**Comment by swiftysix** [comment]
How about getting 3 potential winners via viewer votes and then randomly decide for the final winner? Maybe the 3 "potential" winners would also get a smaller price? Maybe hard to setup...or just a pain 🤣 

Is devpost a github account or a webpage?

**Comment by adilanchian** [comment]
@5upercircuits Devpost has a built in voting system which should hopefully combat against any bot issues or anything like that haha.

In regards to the smaller communities, this should not be an issue as everyone will be apart of Devpost and will be able to see everyone's projects no matter what community they are apart of! This hackathon will not favor streamers with more viewers, it should get everyone on the same playing field :)

Sorry, I am still pretty sick but I hope this makes sense haha. Let me know if it does not.

Also, Devpost is a site! They lead the infrastructure for most MLH hackathons.

**Comment by adilanchian** [comment]
Looks like we have this ready to go :) All voting will be done through the Devpost site by the participants. Thanks everyone!
