### ISSUE TITLE
Decide On Hackathon Name

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Hackathon#4]
Any ideas on a name that can encompass our awesome hackathon?

**Comment by stmoerman** [comment]
Just dropping this in here before I forget; **Hackalong** - to "elevate" the team effort in this hackathon.

**Comment by adilanchian** [comment]
I like that name a lot @DevBowser !

I also thought of something as simple as LiveHacks haha. Opinions?

**Comment by eddiejaoude** [comment]
Both sound good, my 2 cents...`DistributedHackathon` 🤓

**Comment by adilanchian** [comment]
@eddiejaoude what about DistriHacks or DistHack?

**Comment by eddiejaoude** [comment]
`DistHack` sounds good 🤓

**Comment by adilanchian** [comment]
Alright, I am going to throw up a vote for these three options :) See ya in Discord ;)

**Comment by adilanchian** [comment]
Hackalong is the winner! Moving onto the next one.
