### ISSUE TITLE
Recruit at least one other programming/creative streamer to be a part of this event

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Hackathon#5]
I think it would be super awesome if we would be able to include one more streamer from each person to be part of hosting this event. Remember, the more people hosting this hackathon the better!

The only requirement is that they have reached at least Affiliate on Twitch!

**Comment by swiftysix** [comment]
I'm in for hosting the event on 5upercircuits twitch and also doing promotion on any other social network 😃 
How should we setup the hosting? Autohost all streamers who take part in the hackathon? Authost, will stay active as long as that one streamers is online. So, we better maybe organize who hosts which streamer, otherwise everybody will host a single streamer LUL

**Comment by adilanchian** [comment]
Hey @5upercircuits ! Thanks for the comment (So sorry for the late response on this). So happy you are open for promoting. My vision was to have every streaming participating in the event advertise on their streams and social media accounts when possible! At the end of the day, the more people we reach the more of a chance we will all be able to get new viewers and more of a following.

I also thought we could create a community on Twitch where people could go to see ALL the people streaming the hackathon. So we do have Devsauce setup, which I think would be an incredible way to get the word of the community out. I do want to get everyone's idea on this though. 

Finally, this issue was mainly to get everyone helping out to try and bring on one other streamer to the event! The only requirements for them to be able to help is:

1. Must be a Twitch Affiliate/Partner
2. Must be a Creative/Programming/Hardware streamer

Let me know if you have any questions or concerns!
