### ISSUE TITLE
Create a marketing piece for the event

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Hackathon#6]
It would be really awesome to create a marketing piece that we could all advertise on our social media platforms and channel.

**Comment by stmoerman** [comment]
By no means am I anything close to an artist, illustrator or graphic designer, but I think we could do something really cool to brand it and use a strong logo to promote the event. 

![logo-concept](https://user-images.githubusercontent.com/21365172/41157901-5fa9dfd6-6b27-11e8-9b5a-4cb944ce46a5.jpg)

**Comment by adilanchian** [comment]
Yo @DevBowser thanks for putting this together! This is super sick haha. I agree, an eye catching logo that can show that we are doing a hackathon that is being streamed would be incredible.

Once piece of feedback I do have here, I think it would be cool to replace the larger camera with a webcam as we are streaming on webcams now a days haha. 

Thanks again this is sick.

**Comment by Neoplatonist** [comment]
Hi guys, here is my wife's idea for a logo with the theme of "Broadening Horizons". Which emphasizes the resume builder aspect or personal growth. The tagline can be changed for each Hackalong based on the chosen theme. 


![hackalong horizon-01](https://user-images.githubusercontent.com/16985758/41189330-307695de-6c07-11e8-96eb-f3044fb27593.png)

**Comment by eddiejaoude** [comment]
Love all the ideas coming out for this ❤️

**Comment by stmoerman** [comment]
@Neoplatonist Love the work your wife has done, really cool usage of colors and perspective on the theme of the hackathon.

**Comment by adilanchian** [comment]
Huge dan @Neoplatonist ! In my opinion, I would say this is our logo. Its perfect haha. Will throw a vote up in Discord and see what others think :)

Another thing I wanted to add is some banner for social media and the site. This would be great for that if we could "banner-ize" it per say haha

Thanks again!

**Comment by adilanchian** [comment]
Looks like that will be our logo! Will wait for @Neoplatonist's input before closing this in regards to the banner :)

**Comment by adilanchian** [comment]
![screen shot 2018-06-11 at 7 56 31 am](https://user-images.githubusercontent.com/13204620/41232757-fe7edb08-6d4c-11e8-80c5-ee27409fc193.png)

Just throwing this here as well for reference for Devpost's requirements

**Comment by Neoplatonist** [comment]
My wife said she can make a banner too. :grinning: Though we are out of town this week. When do you need it by?

**Comment by adilanchian** [comment]
This is siiiiickkk. @Neoplatonist ASAP man. The sooner the better for sure. I am slowly piecing together the Devpost site and would like us to launch by next week if possible. 

Thanks again man! If she is cool with us adding her name to the contributors list, let me know! Would love to add her.

**Comment by swiftysix** [comment]
Regarding marketing, I think it would be cool to kinda collect all tools/brands that streamers will most likely use during the hackathon.
Let's call it promo buddys (no idea if the term exists), so we could approach these companies/influencers on Twitter. Companies might want to promote it because it presents their brand and hackalong will get more exposure. What do you think?

**Comment by adilanchian** [comment]
@5upercircuits this was my plan! We could approach them to see if they would be interested in giving away like a free course or something depending on the brand. We would just advertise them as a supporter of Hackalong!

**Comment by Neoplatonist** [comment]
@adilanchian My apologies for the wait! She said it is fine to add her to the contributor's list as Megan Johnston.

![hackalong horizon banner-01](https://user-images.githubusercontent.com/16985758/41507387-9a82c8ba-726c-11e8-8ede-e9a501d1fc2e.jpg)

**Comment by adilanchian** [comment]
Holy this is SWEEET @Neoplatonist Thank you so much for this :) and thank Megan as well!

**Comment by adilanchian** [comment]
Going to go ahead and close up this issue as we have the two main things out of the way. If there is a need for more assets, I will plan on adding the issues :) Thanks again everyone!
