### ISSUE TITLE
Prize ideas

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Hackathon#7]
This is a big one and it depends on how we decide to finalize the themes, but what I have imagined is so:

Prizes For:
- Project with overall most votes
- Top voted project for theme x,y,z

It would be awesome to have prizes based on each theme. Depending on issue #2, we can reach out to potential sponsors who might be willing to contribute some sort of prize.
Let the discussions begin!

**Comment by adilanchian** [comment]
I want to start this thread up with a list of ideas for who we may be able to contact to see if there are some prizes we can get sponsored? This may be far fetched, but I think is a bit possible! Please just add a list to your comment :)

- NodeHost (https://cloud.nodehost.ca/)
- PluralSight (Code School: https://www.pluralsight.com/codeschool)
- Some coolio keyboard (+mouse combo maybe?)
- New monitor
- Pair of headphones
- Subscription to a music service 
- Amazon gift card

**Comment by Neoplatonist** [comment]
I came across this list of sponsors: https://github.com/raynesio/hackathon-sponsorship

**Comment by adilanchian** [comment]
This is ballin @Neoplatonist ! We should reach out to as many of these as possible.

**Comment by staghouse** [comment]
I have $150 worth of iTunes gift cards (6x $25) that have been collecting dust for months. More than happy to give this up to the event no charge

**Comment by adilanchian** [comment]
^^^ Love this. Lets keep this in mind for some prizes for sure.

**Comment by adilanchian** [comment]
### Prizes
- 1 FREE Month Of TeamTreeHouse Subscription https://teamtreehouse.com/ (THERE IS ONLY ONE COPY OF THIS) 
- 1 FREE MONTH of PluralSight Subscription (https://www.pluralsight.com/pricing) - Logitech G602 Wireless Gaming Mouse
- Each member of your team will win the following: - Logitech HD Pro Webcam C920
- DREVO Calibur 71-Key RGB LED Backlit Wireless Bluetooth 4.0/USB Wired Gaming Mechanical Keyboard
