### ISSUE TITLE
Review initial pass on hackathon description

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Hackathon#8]
Hey everyone! 

I have posted the link of the temporary hackathon page within the Discord channel. Please take a look at it (all the tabs) and please add your feedback! There a couple points missing, and I do hope we can get them figured out. Thanks in advance!

**Comment by stmoerman** [comment]
Besides the typo in the requirements, I think the description is well done. Do we have a way to link it back to Twitch for people to actually watch the event as well somehow?

edit - added later: What I suggest we do is add a paragraph in which we describe ways for people (streamers) that we have potentially missed on Twitch to join the hackathon. As for requirements, I want to see if we can come down with a way to review the code. There's a lot of platforms people could potentially use i.e. GitHub, GitLab, Bitbucket etc. which could make the process time consuming and very scattered.

**Comment by adilanchian** [comment]
Thanks for the feedback @DevBowser :)

1. Yes! I thinking of linking a community page where we can all add as an event in our streams. This allows everyone to see all the people streaming the event :)

2. Can you elaborate more on the paragraph that would talk to streamers that we have missed on Twitch?

3. I think the best approach would have everyone link their code via Github/GitLab/Bitbucket etc. to their project on Devpost. This will allow the people voting to check out the link directly from their project. Do you think this would work?

4.(My own thought) Where will announcements be made if someone does not want to watch the stream?

5. (My own thought) Any incentive on getting participants to stream? My thought was we could say something like, "Get your work showcased on other streams during the event if you stream what you are doing" or something along those lines. I think it would be AWESOME to see the participants stream their work :)

**Comment by stmoerman** [comment]
@adilanchian Here's some elaboration on 2. I think it would be great if we could write a paragraph that allows people we have not invited to participate yet. Maybe an invite link to the Discord so they can request information or another way to contact us and let us know they want to participate as a streamer for the hackathon?

Linking it could work yeah, that way we don't enforce someone to use a platform they don't like.

We could use the community page to make announcements for people that do not want to watch any stream because I think other platforms would make them too scattered (such as Discord).

**Comment by adilanchian** [comment]
@DevBowser Thats a great idea. I am all for that! Basically have a running update cycle on things that are happening. We can send this through Discord & on the Devpost site

**Comment by adilanchian** [comment]
Alright we are ready to launch this bad boy. If you have any other questions, please message on Discord or open a new issue here to collab.
